---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
      nodePort: 31000
    - name: "jnlp"
      port: 50000
      targetPort: 50000
      nodePort: 31001
  selector:
    app: jenkins